### ISSUE TITLE
Feedback link goes to feedback form

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#1]
When I'm redirected from a Caseflow application I should see a feedback form.
- [ ] This form should have a title: "We welcome your feedback"
- [ ] This form should have introductory copy: "Your comments will help us improve this tool for everyone"
- [ ] This form should have a free-input text field.
- [ ] The free input field should have a description (refer to the mockup)
- [ ] This form should have a submit button allowing the user to submit their feedback.
- [ ] When I click on a submit button, I should see a confirmation page and my feedback should be saved in a database and with the application it refers to.

![image](https://cloud.githubusercontent.com/assets/6335546/19771108/c31a7490-9c2f-11e6-9977-590b5161dcec.png)

![image](https://cloud.githubusercontent.com/assets/6335546/19771263/52b9fc60-9c30-11e6-8dd1-f02fb4cc70f7.png)

**Comment by amprokop** [comment]
We'll need a table with the following columns: feedback, application, timestamps, username (leave it empty). User information will be added to feedback later.

**Comment by amprokop** [comment]
From @shanear: look at the user object on Certification and potentially move that back to caseflow-commons.

**Comment by msknee** [comment]
@amprokop @KHarshawat here is the updated design for the feedback form:

![general feedback form 18](https://cloud.githubusercontent.com/assets/1178390/20193917/289e5d2a-a75e-11e6-990e-8f2ae7bf60f6.png)

**Comment by KHarshawat** [comment]
So beauteous!!!

**Comment by astewarttistatech** [comment]
Unfortunately this does not match the mockups. @amprokop @shanear  @nemodjuric  I suggest the scope be changed.

See attached. 
<img width="594" alt="screen shot 2016-12-02 at 2 49 21 pm" src="https://cloud.githubusercontent.com/assets/23038505/20848143/cc5ec822-b89e-11e6-9a77-47e129e93be8.png">

**Comment by amprokop** [comment]
@astewarttistatech — what doesn't match? We added the contact email form field in a later issue.

**Comment by amprokop** [comment]
@astewarttistatech — can you add more details or revalidate?

**Comment by shanear** [comment]
@astewarttistatech @amprokop 

The "Contact Email" part was added in a later issue, so it wasn't on these mocks. These two are matching enough, and since the logic is :+1: well close this out and handle any design tweaks in a later issue.

Thanks for the screenshot and validation @astewarttistatech
