### ISSUE TITLE
User | Feedback Form | Add a character limit to "Comment" field

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-feedback#103]
As a Product Support Analyst, I would like to limit the amount of characters that can be entered for feedback comments on the User Feedback page so that a user providing feedback is unable to give unlimited amount of information and prevent overflow on the Admin Feedback page.

# Acceptance Criteria
1. Verify that a maximum of 2000 can be entered in the "Comments" field.
1. Verify that the following maximum character limit message is displayed as the characters are entered into the "Comments" field (Refer to Mockup):
     > [MaxCharacters - TotalUsedCharacters] characters remaining

# Mockups
![image](https://cloud.githubusercontent.com/assets/23063044/22359934/7e3c7918-e419-11e6-88ed-afb0aae34216.png)

# Related Stories
n/a

**Comment by nemodjuric** [comment]
@Chingujo @shellicious @lakohl Do you guys have any comments/suggestions on this?

**Comment by msknee** [comment]
LGTM

**Comment by Chingujo** [comment]
@nemodjuric 
Final say on character limit" 

Update***: Should match the limit in certification 

![user feedback embedded alert](https://cloud.githubusercontent.com/assets/23316107/22439755/e142955a-e6fe-11e6-9266-d98e96f756a8.png)

**Comment by ghost** [comment]
Works on `demo`!:
<img width="581" alt="screen shot 2017-01-31 at 16 03 29" src="https://cloud.githubusercontent.com/assets/18075411/22484312/e02b0cd0-e7ce-11e6-8d53-c04ef1a03b63.png">
<img width="974" alt="screen shot 2017-01-31 at 16 03 37" src="https://cloud.githubusercontent.com/assets/18075411/22484313/e02cd358-e7ce-11e6-9d55-7d8a918966fc.png">
