### ISSUE TITLE
User | Paramaters are passed to the Subject

### ISSUE THREAD

**Issue by astewarttistatech** [department-of-veterans-affairs/caseflow-feedback#104]
**Description:**

As a user in Feedback if you add a "/" to the end of the URL and whatever text you want, that will be displayed in the "Tell us about your experience with Caseflow Certification" header. 

**Expected:**
Header is supposed to remain unchanged. Possibly an error page should result. 

**Browser Found:** Firefox
**Environment Found:** UAT

**Steps to Recreate:**
1. Go to https://feedback.cf.uat.ds.va.gov/?redirect=https%3A%2F%2Fcertification.cf.uat.ds.va.gov%2Fcertifications%2F2765748&subject=Caseflow+Certification/

Or access Feedback from one of the products.

2. At the end of the URL add a "/" and any random text
3. Validate that the "Tell us about your experience with Caseflow Certification (Efolder)" header changes with everything at the end of the "/".

**Screenshots:**
<img width="1198" alt="screen shot 2017-01-25 at 11 12 12 am" src="https://cloud.githubusercontent.com/assets/23038505/22299106/e762e5b4-e2f0-11e6-9c51-c5a254ceb893.png">

URL: https://feedback.cf.uat.ds.va.gov/?redirect=https%3A%2F%2Fcertification.cf.uat.ds.va.gov%2Fcertifications%2F2765748&subject=Caseflow+Certification/

**Reported by:** Alexis Stewart

**Comment by amprokop** [comment]
not a bug, we expect that if the user changes the URL querystring param, that will show up in the feedback form. you don't need to put in a `/` to do so.
