### ISSUE TITLE
Internet Explorer unable to display Feedback

### ISSUE THREAD

**Issue by ghost** [department-of-veterans-affairs/caseflow-feedback#115]
When accessing **Feedback** using IE11 or earlier using `Compatibility View`,
I expect the app to look like this:
![lolwut](https://cloud.githubusercontent.com/assets/18075411/23170654/fcc33598-f81d-11e6-94bf-b66b4aa2d7e2.png)

Instead I get this:
![wut](https://cloud.githubusercontent.com/assets/18075411/23170482/4239e938-f81d-11e6-9333-ee573cfeb48b.png)

This is on all environments using IE11:
![iefeedback](https://cloud.githubusercontent.com/assets/18075411/23170678/0f24e8d0-f81e-11e6-89d5-88a9a2ebe77c.png)

**Comment by astewarttistatech** [comment]
@kierachell I assigned it to you because you can access IE

**Comment by ghost** [comment]
**PASSED**
validated in `uat` with _Compatibility View_ on

![fixedfeedback](https://cloud.githubusercontent.com/assets/18075411/23187528/2742cd84-f859-11e6-946f-a13ccb0a48b4.png)
