### ISSUE TITLE
Finalize type treatment of feedback form

### ISSUE THREAD

**Issue by msknee** [department-of-veterans-affairs/caseflow-feedback#12]
Given what I've seen in Caseflow videos, source code, Sketch files, and USWDS, the feedback form type treatment could go in several directions. Which one is most in line with a clear/succinct user experience, and Caseflow styles? 

My vote is for Option 1, as the source code I've seen has non-bolded titles, and I like how the heading 3 styling sets off the call to action for the feedback text entry box.

Option 1: 
- Title: regular weight, 34px
- Body: regular weight, 16px
- Secondary header: 700 weight, 24px (heading 3 from USWDS)

![general feedback form 17](https://cloud.githubusercontent.com/assets/1178390/20070500/7185d062-a4d5-11e6-925b-e8da73d65e4e.png)

Option 2: 
- Title: regular weight, 34px
- Body: regular weight, 16px
- No secondary header, treat the feedback prompt like descriptive text for form fields.

![general feedback form 16](https://cloud.githubusercontent.com/assets/1178390/20070499/7184b6e6-a4d5-11e6-9503-eb1082e7952c.png)

Option 3: 
- Title: 700 weight, 34px
- Body: regular weight, 16px
- Secondary header: 700 weight, 24px (heading 3 from USWDS)

![general feedback form 15](https://cloud.githubusercontent.com/assets/1178390/20070502/718a67da-a4d5-11e6-9a97-393a02346461.png)

**Comment by lakohl** [comment]
@shellicious thanks for the mocks. I think I agree with you - prefer Option 1, but maybe we could move the secondary header up a bit? If you wan to slack me your file I can play with it a bit. @KHarshawat would love to hear your thoughts too, so we can set a baseline together.

**Comment by KHarshawat** [comment]
Ah! I love! Thx @shellicious 

Here's some feedback
- Of those presented, I also like Option 1!
- I agree with @lakohl about bumping the "Tell us about" bit up a little. 
- In "Your comments will help us improve it for everyone." – "it" isn't clear or established. 
- I feel 3 different text styles for a simple form such as this might be a bit excessive and ...
- Similarly I feel like the "We welcome your feedback" feels a little excessive. If you were to remove that line you could put the "Your comments will help improve it for everyone" in the same body text as "What's working well" e.g. 

> ### Tell Us About Your Experience With Caseflow Certification
> 
> What's working well? What's not working? Your comments will help improve the tool for everyone.

**Comment by KHarshawat** [comment]
Also I'm not sure that the lack of bolded titles is intentional. There's an issue to fix this: https://github.com/department-of-veterans-affairs/caseflow-commons/issues/9

**Comment by msknee** [comment]
Thanks for weighing in, everyone! 

We have consensus around @KHarshawat suggestion, plus I've decided to stick with bolded titles:

![general feedback form 18](https://cloud.githubusercontent.com/assets/1178390/20193890/03356eac-a75e-11e6-9147-a8d12e2bf296.png)
