### ISSUE TITLE
Confirmation: Update Styling, Change Back to Close

### ISSUE THREAD

**Issue by shanear** [department-of-veterans-affairs/caseflow-feedback#132]
When users click on "Send Feedback" it opens a new window. When they complete the feedback and click "Back to X" button it redirects the new window they have open back to where they came from, leaving a new window open that they don't seem like they go back to. 

## **AC**

1. Verify the h1 is centered
1.  Verify the h1 reads: "Thank you" (not "Thank You", attached mock is wrong)
1.  Verify the h1 follows font styling for message title: Sans Source Pro, Bold, 52px
1.  Verify the second line of copy: 'Your feedback has been successfully.....' is in USWDS Lead paragraph styling: Sans Source Pro, Regular, 22px
1. Verify the button label displays:
> Close Feedback
1. Verify that the window closes when the user clicks "Close Feedback" (if Feedback is accessed from Caseflow) _or_
1. Verify the button is not there if Feedback is accessed directly from the browser

## **Mock**
![3e9dff86-267f-11e7-9fbc-41bb6afcd819](https://cloud.githubusercontent.com/assets/4975959/25285518/82eef902-2688-11e7-9cfa-ddc7eed04d49.png)

**Comment by shanear** [comment]
@lakohl not sure where this should go.

**Comment by lakohl** [comment]
@Chingujo let's make time to go over Feedback during the Design meeting

**Comment by lakohl** [comment]
@shanear we are going with your suggested option 2. @Chingujo will provide a mock.

**Comment by Chingujo** [comment]
@lakohl 
Here is the mock for the "Close Feedback" (option 2). Apologies for the delay

## Mock
** Updated to reflect shorter copy 

![close feedback](https://cloud.githubusercontent.com/assets/23316107/25282686/3e9dff86-267f-11e7-9fbc-41bb6afcd819.png)

**Comment by lakohl** [comment]
@Chingujo could you update the mock at the very top when you adjust the h1?

**Comment by Chingujo** [comment]
Yes =D! Updated to Thank You

**Comment by mmlumba** [comment]
@amprokop removed this AC since QA doesn't validate pixel sizes anymore (designers do):
> Verify the stage is 918 pixels wide

**Comment by ghost** [comment]
**PASSED**

<img width="1129" alt="screen shot 2017-10-27 at 12 51 51 pm" src="https://user-images.githubusercontent.com/18075411/32115671-b3f7888a-bb15-11e7-8291-27844eafcb1b.png">
