### ISSUE TITLE
An error occurred while installing libv8 (3.16.14.13), and Bundler cannot continue.

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-feedback#14]
Related to https://github.com/department-of-veterans-affairs/roadrunner-rails/issues/65

**Comment by nemodjuric** [comment]
Fixed by https://github.com/department-of-veterans-affairs/caseflow-feedback/pull/15

**Comment by shanear** [comment]
no need for formal validation here if you validated it.
