### ISSUE TITLE
Port Functions to feedback and use it to view the admin feedback page

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#141]
## Acceptance Criteria
- Only users who we've granted System Admin access to can see the feedback page

**Comment by nemodjuric** [comment]
To Verify (since we didn't use Functions):
run 'rake db:migrate:reset' 
List of admin users are in db/seeds/admins.yml
Make sure users from this list only are able to see /admin page

**Comment by ghost** [comment]
**PASSED**
```
Admin.new(css_id: "CF_SCOTTY_283").save!
   (0.7ms)  BEGIN
[2017-09-15 09:21:44 -0400]    (0.7ms)  BEGIN
  SQL (0.9ms)  INSERT INTO "admins" ("css_id") VALUES ($1) RETURNING "id"  [["css_id", "CF_SCOTTY_283"]]
[2017-09-15 09:21:44 -0400]   SQL (0.9ms)  INSERT INTO "admins" ("css_id") VALUES ($1) RETURNING "id"  [["css_id", "CF_SCOTTY_283"]]
   (1.2ms)  COMMIT
[2017-09-15 09:21:44 -0400]    (1.2ms)  COMMIT
=> true
```

<img width="1115" alt="screen shot 2017-09-15 at 9 21 54 am" src="https://user-images.githubusercontent.com/18075411/30484122-61178834-99f7-11e7-9414-5f573f321d8c.png">
