### ISSUE TITLE
Ensure all users (even IE 10 & 11) see a success or failure message after submitting feedback

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#147]
From https://github.com/department-of-veterans-affairs/appeals-support/issues/679

```
I'm trying to send this but receive no confirmation that my request was sent or received. I will try a Fourth time. This time with the Caseflow window/program open. If I have successfully sent this multiple times, I truly apologize. But the page just flashes and then appears unchanged without a message, so it looks like it goes nowhere. 
```

## AC
- Success or failure message shows up after attempted feedback submission in all browsers

**Comment by amprokop** [comment]
@nemodjuric — can you follow up with Raven to get more info from the user, and possibly Alexis to try to reproduce in the user's browser if necessary?

**Comment by nemodjuric** [comment]
By Raven:
Unable to reproduce issue.
Spoke with user this morning to confirm if he was still having issues with sending feedback, and he stated that for the past few days he hasn't had any problems with sending feedback.
Things Noted

user is using Chrome
issue is inconsistent
issue is only happening in reader
