### ISSUE TITLE
Tweak fit & finish

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#148]
The feedback app looks a tad messy. 

![image](https://user-images.githubusercontent.com/3781835/31779633-90428aa2-b4c1-11e7-97d3-abde59926e66.png)

## AC
- All form fields and text should be centered within the white container. 
- There should be a paragraph before the first field that reads "What's working well? What's not working? Your comments will help us improve Caseflow for everyone."
- The label for the first field should read "Add your comments. Please don’t put PII here."
- Remove the red, italic "Please refrain from putting PII in this field." 
- The label on the second form field should contain a comma— "If you are having an issue with a specific case number or Veteran ID, please let us know."
- "Cancel" and "Send Feedback" should be horizontally aligned.
- The shade of black currently used for the text of the label on the first field is inexplicably darker than the lines on the rest of the form. The shade of black should be uniform (we use off-black everywhere else)

**Comment by ghost** [comment]
**PASSED**

- It's not _darker_ anymore :|
<img width="923" alt="screen shot 2017-10-23 at 8 58 04 pm" src="https://user-images.githubusercontent.com/18075411/31920154-09173588-b835-11e7-9f43-723b9fe0fe2e.png">
<img width="569" alt="screen shot 2017-10-23 at 8 59 02 pm" src="https://user-images.githubusercontent.com/18075411/31920155-092fa0dc-b835-11e7-8de6-38e2e2e4329d.png">
<img width="568" alt="screen shot 2017-10-23 at 8 59 20 pm" src="https://user-images.githubusercontent.com/18075411/31920158-10d2ae6a-b835-11e7-9e59-5984896e37c1.png">
