### ISSUE TITLE
Feedback Form:  Reroute back if not logged in

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#22]
As Product Support, I want to only receive feedback from users that are logged in so that their username can be captured and sent with their feedback.

### Acceptance Criteria
1. Verify that if the user is not logged in when the Feedback form is rendered, the user is redirected to the log in page.

### Technical Notes
Refer to the Caseflow pages how they handle.

### Initial Notes
We definitely want to grab the username from an existing session and send it along with feedback, but do we want to require authentication to submit feedback?

**Comment by msknee** [comment]
@amprokop what do you mean by authentication?

**Comment by amprokop** [comment]
@shellicious — logging in. Basically, should people just be able to go to `feedback.caseflow.ds.va.gov` (when logged on to the VA network, not on the public internet) and submit feedback without being logged in?

**Comment by shanear** [comment]
@amprokop we should require people to be logged in (IE: have a username). No specific function is required though.

@shellicious what do you think?

**Comment by amprokop** [comment]
Aye aye!

**Comment by amprokop** [comment]
May have been fixed by https://github.com/department-of-veterans-affairs/caseflow-feedback/pull/65, needs testing in UAT. Some environment configuration issues are blocking this.
