### ISSUE TITLE
Add travis yml file to the project

### ISSUE THREAD

**Issue by nemodjuric** [department-of-veterans-affairs/caseflow-feedback#25]
Add travis yml file to the project
Feel free to copy one from efolder or certification

### Sub-Tasks

- [ ] Need to have a working travis build
- [ ] Prevent merges of pull request with a failing travis build.

**Comment by shanear** [comment]
@nemodjuric @amprokop I'm going to set up the github integration here to test this out

**Comment by amprokop** [comment]
travis builds appear to be running now @shanear! did you make the change? works for me.

**Comment by shanear** [comment]
hello travis :hammer:
https://travis-ci.org/department-of-veterans-affairs/caseflow-feedback
