### ISSUE TITLE
Username Menu:  Dropdown should only contain "Sign Out"

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#32]
As Product Owner, I would like to have just the "Sign Out" option in the Username Menu so that user's providing feedback can log out of Caseflow.

Acceptance Criteria
1. Verify that after clicking on the Username Menu, the only option available is "Sign Out".
1. Verify that after clicking on the "Sign Out" menu option, the user is logged out of the system.

### Mockup
![image](https://cloud.githubusercontent.com/assets/3781835/20507119/c40c0dea-b026-11e6-864f-6bd1707917ff.png)

![image](https://cloud.githubusercontent.com/assets/23063044/20774118/e73f3442-b722-11e6-9b6a-31b717d301e4.png)

**Comment by amprokop** [comment]
I imported the top-right menu from other Caseflow apps, but all of the menu items had dependencies, so i didn't import them.

Certification has "What's new", "Feedback", and "Sign out". Will we need any of these? Perhaps just "Sign out"?

pushing to @shellicious and @shanear. Unless we want to give folks the option to send feedback for the feedback app (which is easy enough!), "Sign Out" is the only obvious choice for importation.

**Comment by msknee** [comment]
Just sign out sounds right to me

**Comment by nemodjuric** [comment]
Per discussion I had with @shanear:
@KHarshawat @shellicious @lakohl Where should user be redirected to once the Sign Out button was clicked?

**Comment by lakohl** [comment]
@nemodjuric it seems like they would have to go back to the CSS login screen as that is where they 'Sign In', no?

**Comment by nemodjuric** [comment]
@shanear What are your thoughts?

**Comment by shanear** [comment]
The CSS login screen is good. Just note, that if it hasn't been 30 min, they wont actually be signed off.

**Comment by nemodjuric** [comment]
@shanear Is this something that we have to handle in Feedback as well? Time the session? Or just redirect them and let CSS handle it?

**Comment by shanear** [comment]
No, we also handle session timeouts on our end here:
https://github.com/department-of-veterans-affairs/caseflow-feedback/blob/master/config/initializers/session_store.rb

**Comment by ghost** [comment]
Well, can't really see it in `demo` cause...`demo`
<img width="299" alt="screen shot 2017-01-06 at 14 00 35" src="https://cloud.githubusercontent.com/assets/18075411/21729324/a6ffbd8a-d418-11e6-9ddf-ffde34b56cb1.png">
obligatory `can't validate this` ping @shanear

**Comment by astewarttistatech** [comment]
Based on @kierachell 's comment, is it safe to assume that we need to slap a label of environment on this issue?

**Comment by shanear** [comment]
Validated on UAT. Works!
