### ISSUE TITLE
Technical:  Add Analytics to application

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#4]
As a developer, I want to know when users are performing certain actions on the feedback form so that I obtain metrics, monitor activity and/or make additional improvements.

### Acceptance Criteria
1. Verify that all visits to the form are being tracked to include the application that sent the user to the feedback form (count, date/time, from application).
1. Verify that the action of clicking the Submit button on the Feedback form is tracked (count, date/time). 
1. Verify that the returning to the redirected application is tracked (count, date/time).
1. Verify that for each action of clicking the Cancel button on the Feedback form is tracked (count, date/time).
1. Verify that for each action of clicking on the submit additional feedback link is tracked (count, date/time).

_This depends on many other stories to be completed first_

**Comment by nikitarockz** [comment]
@KHarshawat @cmgiven For each of the analytics that you want to track, are you looking to just have a count for all items or would you like to also know the date and time a particular action occurred?  This would give you additional metric information.

**Comment by KHarshawat** [comment]
Up to @cmgiven but I'd say the more data the better. I believe date/time is automatically collected w/ Google Analytics tho.

**Comment by cmgiven** [comment]
Yes, if Google Analytics we are looking to track each of these things as an event, which should be associated with a user session.

**Comment by amprokop** [comment]
@nemodjuric, wanna take this on?

**Comment by nemodjuric** [comment]
@amprokop  On it.
