### ISSUE TITLE
Feedback Form: Adjust the container size of the Feedback Comment and Email Address

### ISSUE THREAD

**Issue by msknee** [department-of-veterans-affairs/caseflow-feedback#47]
As Caseflow user, I would like to have container size and labeling for the Feedback Comment and Email Address fields adjusted so that the form appears more aesthetically proportioned.

### Acceptance Criteria
1. Verify that the Feedback Comment container size has been adjusted to the following:  White container, centered on the page, and 458px wide. (refer to mockup)
1. Verify that the width of `input-type-textarea` and `input-type-text` of the Feedback Comment field matches the US Web Design Standards.
1. Verify that the width of `input-type-textarea` and `input-type-text` of the Email Address field matches the US Web Design Standards.

### Mockup
![image](https://cloud.githubusercontent.com/assets/23063044/20805585/4dbafa24-b7c5-11e6-896b-b680623c19be.png)

## Relate Issues
Per discussion with @amprokop on #46.

**Comment by nikitarockz** [comment]
@shellicious would you by any chance have an updated mockup with this change?

**Comment by msknee** [comment]
@nikitarockz I do not, since the change is pretty straightforward. @nemodjuric do you need a mock?

**Comment by nikitarockz** [comment]
@shellicious No worries.  I dropped one in there real quick.  I just like to be consistent and believe a picture ensures the worded vision is clear.  Please check out what I did to make sure this is what you were thinking.

**Comment by msknee** [comment]
@nikitarockz thanks for the first pass! @nemodjuric, take a look at this mock:

![general feedback form](https://cloud.githubusercontent.com/assets/1178390/20785042/e1220636-b752-11e6-964b-633ab1c3012c.png)

**Comment by msknee** [comment]
@KHarshawat what's the standard width of the white container in Caseflow?

**Comment by KHarshawat** [comment]
@shellicious For the main white content area in Certification/Dispatch/eX it's 918px in my mocks and that's what my inspector tells me when i look at the deployed app. Given that this form is so small though, using a width of 918 seems excessive. What are your thoughts on making it much narrower? Perhaps 458px and centered? You'd have something that looks like this:

![image](https://cloud.githubusercontent.com/assets/6335546/20800936/37c502f6-b7b5-11e6-9896-e9a7fa68f084.png)

Using 458px also makes it work well with the standard width of text input boxes in USWDS.

**Comment by amprokop** [comment]
+1 to the level of detail found in the discussion here. It seems like what we really wanted was to make the container less wide, not just to make the textfields have equal width. That wouldn't have been clear to me without some width figures and explicit discussion. Thanks, @shellicious @KHarshawat and @nikitarockz!

**Comment by amprokop** [comment]
One more request, possibly for @shellicious once she makes a final decision— can we update the main issue description up top to reflect these details?

**Comment by msknee** [comment]
@KHarshawat @amprokop 

Container width of 458px and centered sounds good to me! Let's try it and if it looks wonky when deployed, we can try the width of 918 px. Updated instructions, let me know if there are other open questions.

**Comment by nikitarockz** [comment]
@shellicious @KHarshawat Based on this new mockup as compared to what I am seeing currently on the demo site, not only is the dimensions of the feedback comment container changing but so is the size of the Email field, Email labeling, header size and positioning, and the overall dimensions of the form.  Here's the way it currently looks:

![image](https://cloud.githubusercontent.com/assets/23063044/20836903/83705560-b86f-11e6-8c40-62f408c040e4.png)
 
Am I correct in my statement?  Do you want the form to look like this current mockup?

**Comment by KHarshawat** [comment]
@nikitarockz the width of `"input-type-textarea`  and `input-type-text` should not divert from US Web Design Standards. Based on what's in the demo environment the width of this field was customized but it should not be to stay consistent with the rest of the USWDS.

Further by using 458px as I mentioned above these forms should look great.

**Comment by nikitarockz** [comment]
@shellicious Do you feel that the Acceptance Criteria is complete?

**Comment by msknee** [comment]
@nikitarockz Because I don't think USWDS specifies exact widths of form fields, the criteria should be: the width of the email field should be the same as the width of the feedback text field. The width of the container should be 458px. I'm not sure what the padding between the edge of the container and the form fields is, but that will inform the exact width of both the email field and feedback text field. @KHarshawat, do you know what the standard padding should be?

**Comment by KHarshawat** [comment]
30px padding all around just like everywhere else. Shouldn't need to be overwritten for this.

**Comment by msknee** [comment]
@nemodjuric could you post a screenshot of the work in progress? @KHarshawat and @lakohl and I were discussing smaller container widths in another thread, and it would be good to see how the 458px width is working out. Thanks!

**Comment by nemodjuric** [comment]
![caseflow feedback](https://cloud.githubusercontent.com/assets/4960030/21402753/f6dbfe10-c787-11e6-8fb4-92b378267a4a.png)

This was in FF 50
@shellicious

**Comment by KHarshawat** [comment]
So pretty!

**Comment by ghost** [comment]
Looks good in demo, renders appropriate CSS for ```.feedback``` width and padding.

**Comment by ghost** [comment]
Reopened with clarified specifications:
as per @KHarshawat : 

> can you you make the text area the same as it is in the web design standards then make give the app canvas (white area) 30 px of padding around the sides of it
> I think the width of the text area should be 460px

https://standards.usa.gov/form-controls/#text-input

**Comment by nemodjuric** [comment]
![caseflow feedback 13](https://cloud.githubusercontent.com/assets/4960030/21621521/670b4c10-d1c7-11e6-9e0d-e2a07c95e4c4.png)
![caseflow feedback 12](https://cloud.githubusercontent.com/assets/4960030/21621522/674e1072-d1c7-11e6-98c9-d3be77030a8f.png)
![caseflow feedback 11](https://cloud.githubusercontent.com/assets/4960030/21621523/67507aec-d1c7-11e6-9790-f94ecf25fafa.png)
![caseflow feedback 10](https://cloud.githubusercontent.com/assets/4960030/21621525/67639208-d1c7-11e6-8f5a-61f3f3e9eec1.png)
![caseflow feedback 9](https://cloud.githubusercontent.com/assets/4960030/21621526/6763ea3c-d1c7-11e6-9c01-117399768da1.png)

**Comment by ghost** [comment]
The text area has a width of `460px` if you include padding:
<img width="1083" alt="screen shot 2017-01-03 at 15 29 20" src="https://cloud.githubusercontent.com/assets/18075411/21622034/a2a9036e-d1c9-11e6-804a-e7ae30e834b0.png">


The canvas does provide `30px` of padding around the text area:
<img width="1065" alt="screen shot 2017-01-03 at 15 30 17" src="https://cloud.githubusercontent.com/assets/18075411/21622065/c0bee602-d1c9-11e6-8d91-80a85d9e627d.png">


Looks much better on a big screen.
