### ISSUE TITLE
Create Cancel link

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#5]
As a user I need to be able to cancel out of providing feedback so that I can get back to the application I was redirected from without providing feedback.

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. 
<img width="594" alt="screen shot 2016-12-02 at 2 49 21 pm" src="https://cloud.githubusercontent.com/assets/23038505/20848311/9c865a9c-b89f-11e6-80c3-fb42d1618d19.png">
