### ISSUE TITLE
Notification:  Post Slack notification when new feedback is received

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#50]
As a Product Support member, I want to know when feedback is received via Slack so that our main mode of communication is utilized.

### Acceptance Criteria
1. Verify that when a new feedback is submitted and saved successfully, a slack message is posted on the `#appeals-support` channel with a link to the feedback page.
1. Verify that slack alert contains the following text:  "There are new feedback forms!"
1. Verify that in slack alert the there is a link "Review Feedback".

### Mockup

<img width="723" alt="screen shot 2016-11-30 at 12 51 49 pm" src="https://cloud.githubusercontent.com/assets/23316107/20764364/ddd1caa4-b6fb-11e6-9cf8-0e3d075ded52.png">

### Background
Since the volume of feedback is currently low and Slack is the preferred communication channel, @shellicious suggested creating a Slack integration. The integration should post to the #appeals-feedback room when a new piece of feedback is created and should include the text of the feedback, contact email, and VA username.

Look at https://dsva.slack.com/services/B37JRRQTA for integration steps. Seems fairly simple. We could create a `SlackHelper` and have it fire off the messages when feedback is saved. The actual webhook URL should be set in an environment variable, not checked in to GitHub.

**Comment by amprokop** [comment]
@shanear @KHarshawat  — what are your thoughts on this? IMO the Slack integration might be more useful than the admin page itself, at least in the short term while feedback volume is low. I'm thinking it's fine if we made #appeals-feedback a public room in our account—is there any reason it should be private?

**Comment by KHarshawat** [comment]
In general I think this is a great idea but the only thing I'd be concerned about is if the message/feedback happens to contain PII we shouldn't show it in Slack. Maybe we can just send a notification that there is new feedback with a link to a page behind a login that contains the feedback.

**Comment by KHarshawat** [comment]
In general I think this is a great idea but the only thing I'd be concerned about is if the message/feedback happens to contain PII we shouldn't show it in Slack. Maybe we can just send a notification that there is new feedback with a link to a page behind a login that contains the feedback.

**Comment by amprokop** [comment]
Ok — let's scope this down to just posting a notification that new feedback was received.

**Comment by shanear** [comment]
Add a link too.

**Comment by shanear** [comment]
@amprokop we're sure this is technically possible right? If so, lets just turn this issue into actually implementing this.

**Comment by amprokop** [comment]
@shanear — The only possible constraint I can think of is the ability to make requests to the slack API (open internet) from the VA network. That shouldn't be a problem, right? If so, let's modify this.

**Comment by nikitarockz** [comment]
This will have to be on the "support" channel as the Product support team will be responsible for processing these feedback items.  However, currently, this channel doesn't exist and will need to be created.  Actually, it can be either Feedback or Support but definitely not Product (too much going on there).

**Comment by KHarshawat** [comment]
@nikitarockz #appeals-support already exists :)

**Comment by shanear** [comment]
verifying this in prod
