### ISSUE TITLE
Create a way to see feedback

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#6]
As an administrator I should have a way to see the feedback that has been submitted.

### Acceptance Criteria
- Verify all feedback submitted is present in the table reverse chronological order
- Verify that the User, Feedback content, Application name, and Date are listed correctly for each feedback
- Verify that the admin feedback page is not accessible by non-adminstrators

![](https://cloud.githubusercontent.com/assets/6335546/20727223/acdab312-b646-11e6-9b9e-bd4ba6439fa5.png)

### Technical Notes
- Authentication will be handled with CSS. Users not logged in should be redirected to the SSO endpoint on eFolder Express (see how Caseflow does this)

**Comment by msknee** [comment]
@Chingujo is currently working on this. The plan:

- Rough sketches/wireframe to discuss with me by end of day 11/21
- another chat with @Sjones352 about her / support team needs for a feedback view Tuesday 11/22
- Revise and scale down wireframes Tuesday 11/22 and Wednesday 11/23

**Comment by KHarshawat** [comment]
This sounds great!

**Comment by Chingujo** [comment]
Went over some mocks with Shelly Wednesday. Connected with Alex and Nemo before the holidays.  

Going to transfer mocks to Marvel and will post a link today/early Monday.

**Comment by Chingujo** [comment]
@nikitarockz @shellicious @nemodjuric @astewarttistatech 

Hi everyone! 

Sorry took longer than expected. Here are the high level views of the sign in page and the dash as static files. Will be adding research and the interactive prototype to [#1022](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1022)

## Sign In

![sign in for caseflow](https://cloud.githubusercontent.com/assets/23316107/20680655/f2b1b11c-b56d-11e6-871f-f3a7721290e7.jpg)

## Feedback Dash Home
<img width="613" alt="screen shot 2016-11-28 at 1 41 13 pm" src="https://cloud.githubusercontent.com/assets/23316107/20681194/7b047d5e-b570-11e6-8a81-2071676f070a.png">

**Comment by amprokop** [comment]
For the MVP, we've decided to focus on just getting a basic version of the table. The rest of the functionality will be broken out and prioritized separately in storytime.

We'll implement the table as designed, while leaving the following items out:
-pagination
-"Read More"
-sorting
-the "Notes" column

We'll add one more column:
"Application"

Also, we should verify that this table's visual design matches the USDS Web Design Standards. Is the contrast ratio here 508-compliant?

**Comment by amprokop** [comment]
@shanear and I discussed this on the phone just now.
cc @shellicious @Chingujo @KHarshawat @nemodjuric

**Comment by KHarshawat** [comment]
@amprokop the visual design does not match USWDS but I'm happy to mock this up quickly for MVP

**Comment by amprokop** [comment]
ok @KHarshawat that sounds great. you have a sec to take care of that?

**Comment by KHarshawat** [comment]
yep, doing it now.

**Comment by KHarshawat** [comment]
@amprokop here ya go. Zip/Sketch file attached too for those following along.

[Caseflow Feedback 112916.zip](https://github.com/department-of-veterans-affairs/caseflow-feedback/files/620092/Caseflow.Feedback.112916.zip)
![caseflow feedback admin](https://cloud.githubusercontent.com/assets/6335546/20727223/acdab312-b646-11e6-9b9e-bd4ba6439fa5.png)

**Comment by amprokop** [comment]
@nemodjuric — can you make it so? see @KHarshawat's newest mock

**Comment by amprokop** [comment]
Every feature that's not depicted in the mock in the main description body of this PR should be broken out into separate issues. cc @nikitarockz @Chingujo

**Comment by nemodjuric** [comment]
![caseflowfeedback](https://cloud.githubusercontent.com/assets/4960030/20764446/34f7dda0-b6fc-11e6-908a-a6a970e7035f.png)

**Comment by Chingujo** [comment]
@nemodjuric 

Awesome!! 

Just a quick note. The original mock shows the text in the User, Date, and Application fields top aligned with the first line of the feedback section.

**Comment by KHarshawat** [comment]
@Chingujo that was intentional :) I kinda prefer top aligned than center aligned in this instance. WDYT?

**Comment by Chingujo** [comment]
@KHarshawat 

Apologies =D. +1 on top align.

**Comment by msknee** [comment]
nicely done @KHarshawat!

**Comment by amprokop** [comment]
@nemodjuric — apologies, I didn't notice the comments about the top alignment above when I approved your PR for this. The screenshot you posted has a difference in alignment from the mock. Did you take care of this already? If not, can you open a separate PR to make that alignment change? Thanks!

**Comment by amprokop** [comment]
cc @KHarshawat

**Comment by nemodjuric** [comment]
![caseflowfeedback 1](https://cloud.githubusercontent.com/assets/4960030/20802021/ab65cc4c-b7b8-11e6-89b6-961e119bc948.png)

Firefox makes row lines bold (each 3rd or so). I filed #56 for this. 
@KHarshawat @Chingujo @amprokop @shellicious

**Comment by KHarshawat** [comment]
@nemodjuric is this deployed somewhere where I can inspect it?

**Comment by nemodjuric** [comment]
@KHarshawat It is not. However you can checkout 'fix_feedback_view_#6' if you'd like it to locally deploy it. 
Make sure you add the admin role in initializer.

**Comment by amprokop** [comment]
deployed now. closing.

**Comment by shanear** [comment]
@amprokop can you help alexis validate this?

**Comment by astewarttistatech** [comment]
**PASSED**

Please see attached. The URL is https://dsva-appeals-feedback-demo-1748368704.us-gov-west-1.elb.amazonaws.com/admin

<img width="1232" alt="screen shot 2016-12-02 at 2 58 23 pm" src="https://cloud.githubusercontent.com/assets/23038505/20848463/3929f8b8-b8a0-11e6-9372-b4a2468d2d22.png">
