### ISSUE TITLE
Error Message:  Change the User Feedback error message displayed

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#60]
As a Product Owner, I would like the User Feedback error message displayed updated so that it matches the USWDS standards in form validation error messages and provides consistency within the application.

# Acceptance Criteria 
1. Verify that the following fields have the text "_Required_" next to their labels in red and italacized (refer to mockup):  
    - Feedback Comment
    - Email Address
1. Verify that after clicking on the **_Send Feedback_** button and there's no value in the _"Feedback Comment"_ field, the following error Title and Message is displayed: (Refer to mockup) 
**_Message:_**  Make sure you’ve filled out the comment box below.
1. Verify that after clicking on the **_Send Feedback_** button and there's no value in the "_Email Address_" field, the following error Title and Message is displayed:
**_Message:_**  Make sure you’ve entered a valid email address below.
1. Verify that after clicking on the **_Send Feedback_** button and the value in the "_Email Address_" field is not in an email format, the following error Title and Message is displayed:
**_Message:_**  Make sure you’ve entered a valid email address below.
1. Verify that after clicking on the **_Send Feedback_** button, all fields not meeting required field validation is highlighted/outlined in Red and displayed with its validation error message.  (Refer to mock)
1. Verify that after clicking on the **_Send Feedback_** button, the cursor is taken to the first field with a validation issue.

## Mockup
**_View - Feedback and Email Fields with Required label
![image](https://cloud.githubusercontent.com/assets/23063044/21549505/8dad6b6a-cdc0-11e6-807d-ec7c31d0a745.png)

**_View - Missing Feedback Comment_**
![image](https://cloud.githubusercontent.com/assets/23063044/21549329/88c6c0e8-cdbf-11e6-91b5-ae908950264f.png)

**_View - Missing Email Address_**
![image](https://cloud.githubusercontent.com/assets/23063044/21549200/a52debe0-cdbe-11e6-82ef-6492f35f52c2.png)

**_View - Invalid Email Address_**
![image](https://cloud.githubusercontent.com/assets/23063044/21549252/f4ac09cc-cdbe-11e6-8203-5511f111e2c4.png)

**_View - Missing both Feedback Comment and Email Address_**
![image](https://cloud.githubusercontent.com/assets/23063044/21549433/205f98ee-cdc0-11e6-9e31-837b4b7e74f8.png)

**Comment by msknee** [comment]
@amprokop This should be styled like the USWDS error message, unless there is a Caseflow specific style @KHarshawat @lakohl cc @Chingujo 

https://standards.usa.gov/alerts/

**Comment by msknee** [comment]
Screenshot of USWDS standard error below:

![screen shot 2016-12-05 at 10 16 29 am](https://cloud.githubusercontent.com/assets/1178390/20890165/ed194b50-bad3-11e6-8c83-8719710fa9a2.png)

**Comment by KHarshawat** [comment]
Standard USWDS are great!

**Comment by nikitarockz** [comment]
### Background Notes
Here's the current error view (which was based on copy and paste boilerplate code I think)

![image](https://cloud.githubusercontent.com/assets/3781835/20839827/06eba4c4-b87c-11e6-86b3-ae3fcfddda39.png)

**Comment by nikitarockz** [comment]
**_Sprint Planning Notes:_**  Change this to match the way Certification handles validation.  Add validation that there is an email.

**Comment by lakohl** [comment]
Replace the two lines above 'Tell us about your experience...' with:

<img width="681" alt="screen shot 2016-12-19 at 8 02 52 pm" src="https://cloud.githubusercontent.com/assets/4975959/21334531/4e5c65ca-c626-11e6-88b2-00d953ffe305.png">

**Comment by KHarshawat** [comment]
@lakohl we discussed changing these to form input errors like we use in Certification ...

![image](https://cloud.githubusercontent.com/assets/6335546/21354592/b7c49164-c698-11e6-830e-425b8145f24d.png)

**Comment by lakohl** [comment]
@nikitarockz I agree with Kavi - let's use the error messaging style above. Let's also add _Required_ in red, in the top right corner of the required boxes.

**Comment by nikitarockz** [comment]
@shellicious I have updated the Acceptance Criteria and mockups to reflect our discussed changes from sprint planning.

**Comment by nemodjuric** [comment]
![emailnotvalid](https://cloud.githubusercontent.com/assets/4960030/21539605/84286d0a-cd76-11e6-9406-87d7172dca2f.png)
![emailmissing](https://cloud.githubusercontent.com/assets/4960030/21539606/8428ebb8-cd76-11e6-8c0e-71f00f37f8c9.png)
![feedbackmissing](https://cloud.githubusercontent.com/assets/4960030/21539610/842cfca8-cd76-11e6-9da9-1344e3355d06.png)
![bothmissing](https://cloud.githubusercontent.com/assets/4960030/21539608/842a827a-cd76-11e6-9c00-9bf1e38088e3.png)
![required](https://cloud.githubusercontent.com/assets/4960030/21539607/8429ffa8-cd76-11e6-8949-ddc2f0eba6e8.png)

**Comment by nemodjuric** [comment]
@KHarshawat @lakohl @shellicious @nikitarockz

**Comment by lakohl** [comment]
@nemodjuric we updated how 'Required' appears in Caseflow
<img width="304" alt="screen shot 2016-12-29 at 9 55 56 am" src="https://cloud.githubusercontent.com/assets/4975959/21546511/2e628b80-cdad-11e6-9924-742c5c922826.png">

**Comment by nikitarockz** [comment]
# Acceptance Criteria/Mockups -  Updated
@nemodjuric  I have made the following changes:
1. Update Acceptance Criteria (AC) # 1 showing how the word "Required" should be italicized and without parenthesis.
1. Updated the mockup images to match @lakohl comments.

**Comment by nemodjuric** [comment]
![caseflow feedback 8](https://cloud.githubusercontent.com/assets/4960030/21571599/dc358bda-ce9e-11e6-99f0-d93a13c13130.png)
![caseflow feedback 7](https://cloud.githubusercontent.com/assets/4960030/21571600/dc35e3a0-ce9e-11e6-8d52-79f3b2063dde.png)
![caseflow feedback 6](https://cloud.githubusercontent.com/assets/4960030/21571602/dc370280-ce9e-11e6-9550-89803b77df70.png)
![caseflow feedback 5](https://cloud.githubusercontent.com/assets/4960030/21571603/dc3c3214-ce9e-11e6-80fd-e4f747518282.png)
![caseflow feedback 4](https://cloud.githubusercontent.com/assets/4960030/21571601/dc36f182-ce9e-11e6-84c4-e8a699aced78.png)
Note: Change in sizing of input elements to 46rem (to match USWDS) (Before: container size was 458px). 

@lakohl @KHarshawat @nikitarockz @shellicious

**Comment by lakohl** [comment]
@KHarshawat Do I understand correctly from: https://github.com/department-of-veterans-affairs/caseflow-commons/issues/20 that error messages should start with '_Note:_'?

**Comment by KHarshawat** [comment]
@lakohl and I disucssed in person. These error states do not need to start with "Note:"

**Comment by shanear** [comment]
validated
