### ISSUE TITLE
Get authentication working in UAT

### ISSUE THREAD

**Issue by amprokop** [department-of-veterans-affairs/caseflow-feedback#63]
We need authentication working in UAT. To get this working, we need to configure the `SSO_URL` (see https://github.com/department-of-veterans-affairs/appeals-deployment/pull/239/) and configure Feedback to redirect to the login page if there's no user in the session.

**Comment by shanear** [comment]
@amprokop this wont work until we have the feedback.cf.ds.va.gov domain name, because the auth cookie wont transfer over to an IP.

We shouldn't be modifying /etc/hosts to validate issues. Blocking this one for now.
