### ISSUE TITLE
Admin: Dashboard: Ability to sort and filter various columns

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#68]
As a Product Support Analyst, I want to be able to sort and filter on various columns so that I can quickly find important issues.

### Acceptance Criteria
1. Verify that the following columns can be sorted in ascending and descending order:
   - Date
   - Github Issue
   - User
   - Application
   - Status
1. Verify that the following columns allow for filtering of the its available options values:  
   - Application
   - Status
1. Verify that as you start typing letters into the drop down of the column filter, the options displayed begins to provide a filtered list based on the values typed for the following columns (Type-ahead feature):  
   - Application
   - Status
1. Verify that the Total number of Feedback Items for each column's option value is displayed in the following format:  
     **_Format:_**  [option_value] ([Total Feedback Items])
     **_Example:_**  Completed (13)
 
### Mockups 
![admin feedback filter](https://cloud.githubusercontent.com/assets/23316107/21608389/35080c2c-d18a-11e6-9e1c-c3ddc9c66c86.png)

# Related Stories
Caseflow Feedback | Create Engineering stories to Modify UI and functionality [#1767](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1767)
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow - [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
Questions:
Shouldn't you be able to sort on all columns, including User Name, Application, Status?

Suggestions:

1. Verify that the following columns can be sorted in ascending and descending order:
   - Date
   - Github Issue

1. Verify that as you start typing letters into the drop down, the options displayed begins to provide a filtered list based on the values typed for the following columns:  
   - Application
   - Status
