### ISSUE TITLE
User: Feedback Form: Add PII warning comment and Veteran ID field

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#73]
#As a Product Support Analyst, I would like to warn the user not to add PII in the main feedback comment and add a "Veteran PII" field so that PII can be captured and saved in the proper location.

# Acceptance Criteria 
1. Verify that the following PII warning message is displayed below the _"What's working well...."_ field:
     > Please refrain from putting PII in this box.

1. Verify that the following new field has been added (Refer to mockup):  

     _"If you are having an issue with a specific case number or Veteran ID please let us know. It's safe to put PII in this field."_
1. Verify that the _"If you are having an issue..."_ field value is not copied into the github issue.
1. Verify that the _"If you are having an issue..."_ field value is saved in the database.
1. Verify that the _"If you are having an issue..."_ field value is not required.

## Mockups
**_View - User Feedback Form - New field_**

![screenshot_2](https://cloud.githubusercontent.com/assets/23316107/22211992/043f5e00-e15d-11e6-942e-94f9221b71c6.jpg)

![feedback screen](https://cloud.githubusercontent.com/assets/23316107/22212257/f514f3a8-e15d-11e6-888e-5ce3b079d73a.png)

# Related Story
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
# My Feedback
### Sections with Suggested Changes
- [X] Title - Done
- [X] User Story - refer to Changes
- [X] Acceptance Criteria - Refer to changes
- [X] Mockup - @Chingujo needs updating
- [X] Related Stories - Done

### Comments
Another AC may need to be added if you decide that Feedback items with a status of Complete automatically drop from the page.

### Questions
n/a

### Changes
As a Product Support Analyst, I want to be able to exit the Feedback Detail modal so I can return to the Feedback Admin page to continue working.

# Acceptance Criteria
1. Verify that when the **_Go Back_** link is clicked on the Feedback Detail modal, the modal closes and the Feedback Admin page becomes the active window.
1. Verify that after changing the _"Status"_ field value and clicking the **_Go Back_** link on the Feedback Detail modal, the new value is saved.
1. Verify that after changing the _"Status"_ field valued and clicking the **_Go Back_** link on the Feedback Detail modal, the Feedback Dashboard section shows the updated changes to the _"Status"_ field valued.

**Comment by Chingujo** [comment]
Will update mock as soon as I have an approved/final copy

**Comment by lakohl** [comment]
Please flip flop the PII box and the contact email box. The PII box is not required.

1. Please refrain from putting PII in this box.
2. If you are having an issue with a specific case number or vet ID please let us know. It's safe to put PII in this field.

**Comment by nikitarockz** [comment]
@nemodjuric Sorry for the delay but the Mockup has been finalized and the ACs have been updated to reflect these changes.

**Comment by Chingujo** [comment]
@lakohl @nikitarockz @nemodjuric 

Thanks so much everyone +1 to Nikita mock is all good =D. Apologies on the delay

**Comment by lakohl** [comment]
@nemodjuric if you have not already executed on this could you write 'Veteran ID' instead of 'vet ID' on the copy for the second box. thnx. designing over Slack is sub-optimal

**Comment by Chingujo** [comment]
@lakohl @nemodjuric 

Mock updated to reflect new copy.

**Comment by nemodjuric** [comment]
@lakohl @Chingujo @nikitarockz 
'Required' styling does not look like before.

**Comment by Chingujo** [comment]
@nemodjuric @lakohl @nikitarockz 
Here is what it looks like in the style guide =D. Does this match with what you have? Added it to the mock as well.  

<img width="119" alt="screen shot 2017-01-20 at 7 52 37 am" src="https://cloud.githubusercontent.com/assets/23316107/22150289/3adfcc2a-dee6-11e6-85f4-98e98d5b8bfa.png">

**Comment by nemodjuric** [comment]
@KHarshawat Can you confirm how Required span is supposed to look like? The last time I heard from you was in regard to Caseflow modal (issue 626) and Required was in parenthesis, italic and right after the label. Mock above shows Required aligned with input box edge. Did we change our take on this?

**Comment by Chingujo** [comment]
@nemodjuric 

I was directed to align the "Required" to the top right edge of the input box mid last week, so I believe the mock shows the most up to date decision (at least for feedback). Would love a final confirmation as well @lakohl =D

**Comment by Chingujo** [comment]
@nemodjuric 

Just did a design pow wow with @KHarshawat and got official guidance on the "required." 

All required should look like below:

![screenshot_2](https://cloud.githubusercontent.com/assets/23316107/22211782/3810dd7c-e15c-11e6-9650-6cf51a45e657.jpg)
- [ ] Italicized 
- [ ] No ()



# Text Input boxes
- [ ] For text inputs align it to the top right edge as shown in the above mock and below 

![required](https://cloud.githubusercontent.com/assets/23316107/22211584/795848e8-e15b-11e6-9cf2-5b09426ac778.jpg)


# For no input boxes: 

- [ ] 2 spaces after the last character like shown below 

![required no input box 2](https://cloud.githubusercontent.com/assets/23316107/22211853/8037f0f4-e15c-11e6-92f3-86bff5b8f938.jpg)

**Comment by ghost** [comment]
Phillip confirmed that it looks good 👍 

<img width="677" alt="screen shot 2017-01-30 at 09 19 49" src="https://cloud.githubusercontent.com/assets/18075411/22426444/448daa00-e6cd-11e6-89fb-0903e63c230f.png">
