### ISSUE TITLE
Admin: Dashboard: Add "Github Issue" column as a link to Github ticket

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#75]
As a Product Support Analyst, I want to be able to navigate to a Github issue from the Admin Feedback Dashboard so that I can easily view and make updates to the issue.  

# Acceptance Criteria 
1. Verify that in the Dashboard section, there is a new column _"Github Issue"_.
1. Verify that the _"Github Issue"_ column contains the Feedback item's related github issue number.
1. Verify that the Feedback item's Github Issue number is a link.
1. Verify that after clicking the **_Github Issue Number_** link, that issue item is opened and displayed in a new web browser tab.

# Mockup
**_View - Admin Dashboard - New "Github Issue" column_**
![caseflow feedback admin 6](https://cloud.githubusercontent.com/assets/23316107/22066734/5bf21516-dd5c-11e6-9028-d24ddb7fbf2d.png)

# Related Stories 
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow - [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
Suggested Changes:  Title

Acceptance Criteria
1. Verify that the Feedback item's Github Issue number is a link.
1. Verify that after clicking the Github Issue number link, that issue item is launched and displayed in a new tab.

**Comment by anyakhvost** [comment]
In demo, it will not create an actual Github issue. This can only be fully tested in UAT. Waiting on @ariperez to create a support user and generate the access_token for UAT

**Comment by astewarttistatech** [comment]
Tested in Demo, so far. Still waiting on the access_token for UAT. 

Steps to Validate:
1. Go to admin of Feedback 
2. Validate that the column for Github Issues is present

*Note: Like Anya mentioned, there are no linking issues. Also the spacing seems off, gonna loop @lakohl into it. Please refer to screenshots below. 

Screenshots:
<img width="1259" alt="screen shot 2017-01-24 at 12 27 17 pm" src="https://cloud.githubusercontent.com/assets/23038505/22258744/cb497386-e230-11e6-8b39-9bf4cce8d2c6.png">

**Comment by astewarttistatech** [comment]
Blocked until access_token is generated for UAT testing.

**Comment by astewarttistatech** [comment]
**PASSED** 

Please see below for UAT.

Screenshot:
<img width="944" alt="screen shot 2017-01-25 at 11 58 38 am" src="https://cloud.githubusercontent.com/assets/23038505/22300685/3e5f0546-e2f6-11e6-8eb2-dc6ada88f5bd.png">
<img width="1077" alt="screen shot 2017-01-25 at 11 59 42 am" src="https://cloud.githubusercontent.com/assets/23038505/22300687/4277ab1a-e2f6-11e6-9568-556bfe021b3b.png">
