### ISSUE TITLE
Admin | Logo | Update with Feedback color logo

### ISSUE THREAD

**Issue by Chingujo** [department-of-veterans-affairs/caseflow-feedback#76]
As a Product Owner, I would like the logo to be update to the logo so that it represents the Feedback application and is complies with consistent stylization.

# Acceptance Criteria 
1. Verify that the standard application header is displayed with the following logo elements (Refer to mockup): 
    - **Application Name** - "Caseflow Feedback" 
    - **Application Logo**- [SVG of Caseflow Logo.svg.zip](https://github.com/department-of-veterans-affairs/caseflow-feedback/files/735575/SVG.of.Caseflow.Logo.svg.zip)
1. Verify that the spacing between "Caseflow" and "Feedback" is only one space.

# Mockups 
**_View - Admin Feedback page - correct logo_**
![untitled](https://cloud.githubusercontent.com/assets/23316107/22308174/dcf14d5a-e313-11e6-8a0a-04871d04a070.png)

# Related Stories 
Epic: Feedback Admin View: Ability to view and report incoming feedback form Caseflow - [#1050](https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050)

**Comment by nikitarockz** [comment]
Suggestions - I did name change.

### Acceptance Criteria 
1. Verify that the total number of Feedback form items with the Status of  "Under Review" is displayed. (Refer to mockup)
1. Verify that after changing the status of a feedback item, total number of Under Review Feedback items count is updated approximately.

### Mockups 
<img width="715" alt="screen shot 2016-12-12 at 10 33 28 am" src="https://cloud.githubusercontent.com/assets/23316107/21105100/040724bc-c057-11e6-9d4e-18b29c69cc9d.png">

### Referenced Stories 
https://github.com/department-of-veterans-affairs/appeals-pm/issues/1050

**Comment by KHarshawat-gov** [comment]
[Caseflow Feedback.svg.zip](https://github.com/department-of-veterans-affairs/caseflow-feedback/files/745818/Caseflow.Feedback.svg.zip)

**Comment by astewarttistatech** [comment]
Coloring seems off, like its too opaque, @Chingujo or @KHarshawat-gov  can you double check?

Steps to Validate: 
1. Go to https://feedback.cf.uat.ds.va.gov/ and it's admin page directly and via caseflow and efolder express applications
2. Verify the Caseflow feedback logo matches those in the mocks. 

Screenshots:
<img width="1337" alt="screen shot 2017-02-02 at 6 32 41 pm" src="https://cloud.githubusercontent.com/assets/23038505/22573333/7a2fea32-e976-11e6-8165-b102a934c4fc.png">
<img width="1303" alt="screen shot 2017-02-02 at 6 36 22 pm" src="https://cloud.githubusercontent.com/assets/23038505/22573340/8b6535dc-e976-11e6-8ea6-b7ac8db9923c.png">

**Comment by KHarshawat-gov** [comment]
@astewarttistatech LGTM ... checked against the other logos and it's consistent. This one is just a lighter color.

**Comment by astewarttistatech** [comment]
Ok cool beans. Closing this. 

**PASSED**
