### ISSUE TITLE
Log to stdout instead of rails default production.log

### ISSUE THREAD

**Issue by orischwartz** [department-of-veterans-affairs/caseflow-feedback#79]
> A twelve-factor app never concerns itself with routing or storage of its output stream. It should not attempt to write to or manage logfiles. Instead, each running process writes its event stream, unbuffered, to stdout.

Relevant library https://github.com/heroku/rails_stdout_logging.

See also https://github.com/department-of-veterans-affairs/caseflow/issues/462 and https://github.com/department-of-veterans-affairs/caseflow/pull/558

**Comment by anyakhvost** [comment]
Alan will be validating this.

**Comment by askldjd** [comment]
Validated in UAT env. Notice that as soon as the PR was merged, Cloudwatch stops getting production.log update.

![image](https://cloud.githubusercontent.com/assets/3258724/21431406/19b77524-c835-11e6-8262-7405300cf583.png)
