### ISSUE TITLE
Visual Design of Modals

### ISSUE THREAD

**Issue by KHarshawat** [department-of-veterans-affairs/caseflow-feedback#8]
As an engineer I would like to know what modals look like so I can build them.
- [x] Design Modals

**Comment by msknee** [comment]
This is a bit blocked on not knowing the Caseflow style guide

**Comment by KHarshawat** [comment]
@shellicious since USWDS doesn't have any modals we basically get to make something up :) I'll try to provide you with guidance/feedback if you want to give it a stab!

**Comment by msknee** [comment]
Closing this now that a modal design exists!
