### ISSUE TITLE
Can't submit Feedback in demo environment

### ISSUE THREAD

**Issue by askldjd** [department-of-veterans-affairs/caseflow-feedback#82]
In the demo environment, if you submit a feedback, you will see a Rails error that says "Invalid Token". And if you remove the protect_from_forgery protection, you will see another error that says "Subject Can't Be Blank".

Here are my hacks that hid the problem in the demo environment. I did this quickly since @lakohl has a demo.

Below are the git diff. The changes are pretty simple, and definitely _not_ the right solution.

```
+++ b/app/controllers/application_controller.rb
@@ -1,7 +1,7 @@
 class ApplicationController < ActionController::Base
   # Prevent CSRF attacks by raising an exception.
   # For APIs, you may want to use :null_session instead.
-  protect_from_forgery with: :exception
+  #protect_from_forgery with: :exception
   before_action :setup_fakes
 
   def unauthorized
diff --git a/app/controllers/feedback_controller.rb b/app/controllers/feedback_controller.rb
index 923930b..2f30a63 100644
--- a/app/controllers/feedback_controller.rb
+++ b/app/controllers/feedback_controller.rb
@@ -31,6 +31,7 @@ class FeedbackController < ApplicationController
   end
 
   def feedback_params
+    session[:subject] = session[:subject] || "Caseflow"
     params.require(:feedback)
           .permit(:feedback, :contact_email)
           .merge(subject: session[:subject], username: current_user.display_name)
diff --git a/lib/fakes/initializer.rb b/lib/fakes/initializer.rb
```

**Comment by askldjd** [comment]
Colored version of the diff.

![image](https://cloud.githubusercontent.com/assets/3258724/21400132/a2105eae-c77c-11e6-8463-4dbd3bf8477b.png)

**Comment by amprokop** [comment]
to confirm, @askldjd — this is not affecting prod or uat?

**Comment by askldjd** [comment]
Screenshot of the issue. 
![image](https://cloud.githubusercontent.com/assets/3258724/21402234/a7cb25be-c785-11e6-9b19-0de61309f892.png)

**Comment by askldjd** [comment]
@nemodjuric found the issue. We should remove COOKIE_DOMAIN for demo env.

See https://github.com/department-of-veterans-affairs/appeals-deployment/blob/master/ansible/roles/caseflow-feedback/defaults/main.yml#L40

**Comment by askldjd** [comment]
This issue is addressed by @amprokop from the PR https://github.com/department-of-veterans-affairs/appeals-deployment/pull/303
