### ISSUE TITLE
Certification: Cancellation Modal: Ability to view instructions and report issues

### ISSUE THREAD

**Issue by msknee** [department-of-veterans-affairs/caseflow-feedback#87]
As a Regional Office Caseworker, I want to understand how to cancel a certification and report problems that led to the cancellation in a modal view, so that I can quickly cancel and report problems to the Caseflow team.

## Acceptance Criteria:
1. Verify that the Cancel Certification modal contains the content in the mockup
- A header
- Brief instructions explaining the purpose of the modal.
- “Cancel certification” is bolded within the instructions.
- Question that is marked "Required"
2. Verify that the modal contains radio buttons shown in the mockup.
3. Verify that a form field exists, as shown in the mockup, for entering the Caseworker’s email address, and that it’s marked “Required"
4. Verify that “Go back” closes the modal but does not cancel or exit out of the case being certified.
5. Verify that the “Cancel Certification” button exists as shown in the mockup.

![radio button](https://cloud.githubusercontent.com/assets/1178390/21618452/f7f8757c-d1b8-11e6-8643-81beada00211.png)

**Comment by nikitarockz** [comment]
## Closing
Issues in wrong repository
**_New Issue:_** Certification: Cancellation Modal: Ability to view instructions and report issues - [#626](https://github.com/department-of-veterans-affairs/caseflow/issues/626)
