### ISSUE TITLE
Certification: Cancellation Modal: Ability to select "Other" option for reporting issues

### ISSUE THREAD

**Issue by msknee** [department-of-veterans-affairs/caseflow-feedback#88]
As a Regional Office Caseworker, I want to report problems with certifying a case that are not pre-written options in the cancellation modal, so that I can report problems that the Caseflow team is less aware of.

## Acceptance Criteria:
1. Verify that clicking on the “Other” radio button in the modal:
- expands the modal
- displays a text field marked as “Required”, with copy shown in the mockup
2. Verify that clicking on another radio button:
- Selects the new radio button
- Hides the text field marked as “Required” as well as the copy shown in the mockup
- Decreases the length of the modal to its original size.
3. Verify that if "Other" button is selected but the text field associated with it left blank, that an error message is displayed reminding the Caseworker to fill in the required text field.
4. Verify that when submitted, the text in the other column is saved to the database.

![radio button other](https://cloud.githubusercontent.com/assets/1178390/21618463/04498a50-d1b9-11e6-99aa-86c833b49bc4.png)

# Related Stories
Certification: Cancellation Modal: Ability to view instructions and report issues - [#626](https://github.com/department-of-veterans-affairs/caseflow/issues/626)

**Comment by nikitarockz** [comment]
## Closing
Issues in wrong repository
**_New Issue:_**  Certification: Cancellation Modal: Ability to view instructions and report issues - [#626](https://github.com/department-of-veterans-affairs/caseflow/issues/626)
