### ISSUE TITLE
Certification: Cancellation Modal: Ability to submit data about cancellation problems and view a confirmation page

### ISSUE THREAD

**Issue by msknee** [department-of-veterans-affairs/caseflow-feedback#89]
As a Regional Office Caseworker, I want to cancel a certification and report problems that led to the cancellation in a modal view, so that I can quickly cancel and report problems to the Caseflow team.

## Acceptance Criteria:
1. Verify that the “Cancel Certification” button does the following:
- submits the Caseworker’s radio button selection, optional free text, and email address to a feedback database
- Closes the modal
- Loads a new page confirming the cancellation 
2. Verify that the confirmation page contains the copy shown in the mockup:
- A header
- Brief descriptive text
- A link back to the starting screen of Caseflow for the Caseworker to start certifying a new case

![v4_confirm](https://cloud.githubusercontent.com/assets/1178390/21618370/9c1bb124-d1b8-11e6-9082-18bffe11682b.png)

**Comment by nikitarockz** [comment]
## Closing
Issues in wrong repository
**_New Issue:_** Certification: Cancellation Modal: Ability to submit cancellation - [#631](https://github.com/department-of-veterans-affairs/caseflow/issues/631)
Certification: Cancellation Modal: Ability to view confirmation - [#630](https://github.com/department-of-veterans-affairs/caseflow/issues/630)
