### ISSUE TITLE
Slack | Appeals-Support | Caseflow Feedback Bot |  "Click Here" URL is incorrect

### ISSUE THREAD

**Issue by nikitarockz** [department-of-veterans-affairs/caseflow-feedback#95]
# Description
When you click on feedback link in slack, it gives you an error page. The URL that it is taken you to is wrong (https://feedback.cf.ds.va.govadmin/). 

The correct URL should be: https://feedback.cf.ds.va.gov/admin/.

**Confirmed Environment(s)**
- [ ] Dev
- [ ] Demo
- [ ] UAT
- [x] Prod

**Type of Bug**
- [x] Functional
- [ ] Design
- [ ] Security
- [ ] Tech Improvement

**Severity Level**
- [ ]    5 - Data loss, data corruption or system unavailable
- [ ]    4 - Important functionality is unavailable with no workaround
- [x]    3 - Important functionality is unavailable but has a reasonable workaround
- [ ]    2 - Secondary functionality is unavailable but has a reasonable workaround
- [ ]    1 - Cosmetic issues or some functionality unavailable but has a simple workaround

# Reproductive Steps
1. On appeals-support channel.
1. Click on Caseflow Feedback URL.
1. Gives error page.

# Screenshot 
**_View - Error Message_**
<img width="1280" alt="screen shot 2017-01-11 at 12 37 47 pm" src="https://cloud.githubusercontent.com/assets/23080951/21859870/56f4a6d8-d7fc-11e6-8983-44da5adc2274.png">

# Related Stories
**_Support Issue_**
Slack: Appeals-Support: Caseflow Feedback Bot: "Click Here" URL doesn't launch Admin Feedback page [#3](https://github.com/department-of-veterans-affairs/appeals-support/issues/3)

**Comment by shanear** [comment]
This is fixed by https://github.com/department-of-veterans-affairs/caseflow-feedback/issues/72

**Comment by ghost** [comment]
<img width="514" alt="screen shot 2017-01-27 at 15 30 31" src="https://cloud.githubusercontent.com/assets/18075411/22386554/963d7eae-e4a5-11e6-814e-9e34138904fe.png">
Confirmed
